/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rmonico' at '29/02/16 15:02' with Gradle 2.11
 *
 * @author rmonico, @date 29/02/16 15:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
